(defun binary-search (&optional needle)
  "Locate for insertion in an ordered manner."
  (interactive "sNeedle: ")
  (cl-flet ((midpoint (a b)
              (+ a (/ (- b a) 2)))
            (peek (line)
              (goto-line line)
              (beginning-of-line)
              (word-at-point)))
    (let* ((a (line-number-at-pos))
           (b (save-excursion (end-of-buffer) (line-number-at-pos))))
      (while (> (- b a) 1)
        (let ((mid (midpoint a b)))
          (if (string< needle (peek mid))
              (setq b mid)
            (setq a mid))))
      (goto-line a))))
