* ksqsf's =.emacs.d=

  This configuration has been tested on macOS and Debian.

  NOTE: This configuration only targets Emacs 26.3.  No guarantee
  about forward/backward compatibility.  You can comment out the first
  paragraph in =init.el= if you do want to try.

** Philosophy

   My primary goals are

   * Fast, and responsive
   * Healthy, and easy on the eye
   * Productive, and distraction-free
   * Predictable
   * Stable
   * Maintainable codebase
   * Prefer built-in functionality to third-party packages


   I don't strive to achieve eye-candy and powerfulness, but they are
   good, and may be considered in the future.

** Structure

  There are two kinds of configuration, Module and Volatile.  The
  distinction is (in my mind) very successful.

*** Module

    Modules make up the functionality and keybindings.  They are
    stable and can be byte compiled safely and cleanly.  Ideally, they
    use lexical scoping.

*** Volatile

    Volatile configuration files are more fragile and personal.  They
    are mainly temporary tests or (let's hope not) ugly hacks.  A
    volatile Lisp file should never be byte compiled.  Typically, it's
    dynamically scoped.

** Fonts

  The following fonts are "blessed" in this configuration.

  | Font         | Size | Usage                     |
  |--------------+------+---------------------------|
  | Fira Code    |   14 | General use (non-Chinese) |
  | Iosevka Term |   14 | Tabular content           |

  However, other fonts also seem to work well, like Monaco and Menlo.

** Better Defaults

   These modifications are generally in =prelude-core.el= and
   =prelude-ui.el=.

   User-*very*-visible modifications are listed here.

*** Themes

    The default theme (too bright) was replaced by [[https://srcery-colors.github.io][Srcery]].

    By default, the frame is 92% transparent.

*** Zap up to char

    =M-z= was assigned to =zap-up-to-char=.  You can easily achieve
    what =zap-to-char= does with =M-z <char> C-d=.

    At first, I thought =M-z t= and =M-z f= would be cool, but it
    turned out to be a horrible idea, because one must stop to think
    which key to press.

*** Mode line

    Doom mode line.

*** Quick Completion

    I use Ivy and the Counsel family, as they tend to blend better
    with other modern packages.
